### ISSUE TITLE
Fixing the API Specification

### ISSUE THREAD

**Issue by rstuart85** [humbug-au/bugeye#5]
I think the backend API specification needs to be reviewed and made more concrete. Specifically:
- I don't think there is any need to create a room programatically. Rather, I think a bugeye instance needs to be assigned a role and given some meta data via a configuration file/command line args. Obviously the functionality for a _master_ bugeye is far different for a _in-room_ bugeye. Maybe they should be two different pieces of software or maybe they should be configured as to which role they are? Also, the meta data about the current _in-room_ bugeye should just be a configuration problem. No need to create rooms. The in-room machines an just send stuff to the configured master and it will just accept it with the metadata it's given. 
- I don't know enough about recording video to know how a source should be added. Is this a UI problem or will it be handled by some other mechanism?
- A note on the sockets. Obviously a web socket can only have 2 parties (one at either end) so the backend is acting as a _record and echo_ device. It receives a message from 1 of its clients, records it, and echoes it to all clients. 

That's about it for now. But any other commentary on this document should go here so we can collate and finalise.

Looking for feedback from @rstuart @matheist76 @leesdolphin.

**Comment by software-opal** [comment]
So @rstuart85, We are having 1 'server' per room, which is responsible for serving the website, transcoding and mixing videos.
With this system architecture is there any need for the master server?

I agree that the web sockets should act as you describe - pass messages from the sending client to all other connected clients.

**Comment by rstuart** [comment]
Why did we start a new issue?  Isn't #3 good enough?  If it is can we move the discussion to there please.

**Comment by rstuart85** [comment]
@rstuart When you said "the document I put up", I assumed you meant the API document in the repository. Not an issue. I was referring to the document.

I will now go and read the issue.
